### ISSUE TITLE
kubefire install failed with unable to install script install-prerequisites.sh: exit status 1

### ISSUE THREAD

**Issue by kconde2** [innobead/kubefire#51] opened 2022-02-22 02:22 UTC
**Describe the bug**
Prerequisites installation failed

**To Reproduce**
1. Install kubefire `curl -sfSL https://raw.githubusercontent.com/innobead/kubefire/master/hack/install-release-kubefire.sh | bash`
2. Run `kubefire install --log-level=debug`

**Expected behavior**
I expected to not have error when command execution ends

**Environment**
 - OS version
    - run `cat /etc/os-release`
```shell
cat /etc/os-release
NAME="Zorin OS"
VERSION="16"
ID=zorin
ID_LIKE=ubuntu
PRETTY_NAME="Zorin OS 16"
VERSION_ID="16"
HOME_URL="https://zorin.com/os/"
SUPPORT_URL="https://zorin.com/help/"
BUG_REPORT_URL="https://zorin.com/os/feedback/"
PRIVACY_POLICY_URL="https://zorin.com/legal/privacy/"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
 ```
 
 - Kubefire version
    - run `kubefire version`
```shell
Version: v0.3.6
Build: 9413383-20210502190639
```
 
 - Kubefire runtime info
    - run `kubefire info` 
```shell
CONTAINERD         	IGNITE             	CNI                	RUNC                   	CNIPLUGIN                              
 (expected: v1.4.4)	 (expected: v0.9.0)	 (expected: v0.9.1)	 (expected: 1.0.0-rc93)	 (expected: 0.4.0/kubefire-cni-bridge)
```
**Additional context**
![image](https://user-images.githubusercontent.com/43377621/155050594-d973906a-1a0f-4008-b606-d131d162387b.png)

Thanks in advance for your help

**Comment by innobead** [comment] 2022-02-24 10:23
this is a duplicate of https://github.com/innobead/kubefire/pull/49. We will release the next patch soon.

**Closed by innobead** 2022-02-24 10:23 UTC
Labels: bug
